
### BadiRate script file for BDI-spT-ML
#iter 1, no seed

cd ~/Desktop/Proj_vanessa_assembly/output/10b_badirate/badirate_orthogroups/

mkdir ../raw_outputs/spT

for file in ./*
do
echo ${file}
	~/perl5/perlbrew/perls/perl-5.16.3/bin/perl /Applications/badirate-1.35/BadiRate.pl -start_val 1 -rmodel BDI -bmodel "10->9" -ep ML -treefile /Users/karin/Desktop/Proj_vanessa_assembly/output/10b_badirate/input/orthofinder_210624_ultra_mod.nw -sizefile ./${file} -anc -outlier -out ../raw_outputs/spT/${file}.spT01.bd

done
