### BadiRate script file for BDI-spM-ML
#iter 2, seed

cd ~/Desktop/Proj_vanessa_assembly/output/10b_badirate/badirate_orthogroups/

mkdir ../raw_outputs/spM

for file in ./*
do
echo ${file}
	~/perl5/perlbrew/perls/perl-5.16.3/bin/perl /Applications/badirate-1.35/BadiRate.pl -seed 20180808 -start_val 1 -rmodel BDI -bmodel "10->8_17->1" -ep ML -treefile /Users/karin/Desktop/Proj_vanessa_assembly/output/10b_badirate/input/orthofinder_210624_ultra_mod.nw -sizefile ./${file} -anc -outlier -out ../raw_outputs/spM/${file}.spM02.bd

done